// This file was generated by the XState CLI, please do not edit it manually.
import { createMachine } from 'xstate5';

const machine = createMachine(
  {
    id: 'bananaDispensingMachine',
    initial: 'idle',
    states: {
      idle: {
        description:
          'The machine is idle and waiting for a user to insert coins or a request to dispense a banana.',
        on: {
          INSERT_COINS: {
            target: 'waitingForSelection',
            reenter: true,
          },
          DISPENSE_BANANA: {
            target: 'idle',
            reenter: true,
          },
        },
      },
      waitingForSelection: {
        description:
          'The machine is waiting for the user to select the number of bananas to dispense.',
        on: {
          SELECT_ONE: {
            target: 'dispensingOneBanana',
            reenter: true,
          },
          SELECT_THREE: {
            target: 'dispensingThreeBananas',
            reenter: true,
          },
          CANCEL: {
            target: 'idle',
            reenter: true,
          },
          SELECT_TWO: {
            target: 'dispensingTwoBananas',
            reenter: true,
          },
        },
      },
      dispensingOneBanana: {
        description: 'The machine is dispensing one banana to the user.',
        on: {
          DISPENSE_COMPLETE: {
            target: 'idle',
            reenter: true,
          },
        },
      },
      dispensingThreeBananas: {
        description: 'The machine is dispensing three bananas to the user.',
        on: {
          DISPENSE_COMPLETE: {
            target: 'idle',
            reenter: true,
          },
        },
      },
      dispensingTwoBananas: {
        description: 'The machine is dispensing two bananas to the user.',
        on: {
          DISPENSE_COMPLETE: {
            target: 'idle',
            reenter: true,
          },
        },
      },
    },
    types: {
      events: {} as
        | { type: 'CANCEL' }
        | { type: 'SELECT_ONE' }
        | { type: 'SELECT_TWO' }
        | { type: 'INSERT_COINS' }
        | { type: 'SELECT_THREE' }
        | { type: 'DISPENSE_BANANA' }
        | { type: 'DISPENSE_COMPLETE' },
    },
  },
  {
    actions: {},
    actors: {},
    guards: {},
    delays: {},
  },
);

export const skyConfig = {
  actorId: 'bd8947a6-d615-465a-bad7-cb1e73dbb151',
  machine,
};
