// This file was generated by the XState CLI, please do not edit it manually.
import { createMachine } from 'xstate';

const machine = createMachine({
  id: 'bananaDispensingMachine',
  initial: 'idle',
  states: {
    idle: {
      description:
        'The machine is idle and waiting for a user to insert coins or a request to dispense a banana.',
      on: {
        INSERT_COINS: {
          target: 'waitingForSelection',
        },
        DISPENSE_BANANA: {
          target: 'idle',
          internal: false,
        },
      },
    },
    waitingForSelection: {
      description:
        'The machine is waiting for the user to select the number of bananas to dispense.',
      on: {
        SELECT_ONE: {
          target: 'dispensingOneBanana',
        },
        SELECT_TWO: {
          target: 'dispensingTwoBananas',
        },
        SELECT_THREE: {
          target: 'dispensingThreeBananas',
        },
        CANCEL: {
          target: 'idle',
        },
      },
    },
    dispensingOneBanana: {
      description: 'The machine is dispensing one banana to the user.',
      on: {
        DISPENSE_COMPLETE: {
          target: 'idle',
        },
      },
    },
    dispensingTwoBananas: {
      description: 'The machine is dispensing two bananas to the user.',
      on: {
        DISPENSE_COMPLETE: {
          target: 'idle',
        },
      },
    },
    dispensingThreeBananas: {
      description: 'The machine is dispensing three bananas to the user.',
      on: {
        DISPENSE_COMPLETE: {
          target: 'idle',
        },
      },
    },
  },
  predictableActionArguments: true,
  preserveActionOrder: true,
  tsTypes: {} as import('./monsterMachine.fetched.typegen').Typegen0,
});

export const fetchedConfig = {
  actorId: '5175233c-b197-4ed1-ac8d-3fe63a87c856',
  machine,
};
