import { createMachine } from 'xstate';

// This file was generated by the XState CLI, please do not edit it manually.
const workflowId = 'df576bcd-978f-4b83-a0c7-4932c3169073';

const fetchedMachine = createMachine({
  id: 'Toggle Machine',
  initial: 'Off',
  states: {
    Off: {
      on: {
        toggle: {
          target: 'On',
        },
      },
    },
    On: {
      on: {
        toggle: {
          target: 'Off',
        },
      },
    },
  },
  schema: { events: {} as { type: 'toggle' } },
  predictableActionArguments: true,
  preserveActionOrder: true,
  tsTypes: {} as import('./monsterMachine.fetched.typegen').Typegen0,
});
export const fetchedConfig = { workflowId, fetchedMachine };
