import { createMachine } from 'xstate';

// This file was generated by the XState CLI, please do not edit it manually.
export default createMachine({
  id: 'Monster',
  initial: 'not scary',
  states: {
    'not scary': {
      on: {
        hungry: {
          target: 'scary',
        },
      },
    },
    scary: {},
  },
  schema: { events: {} as { type: 'hungry' } },
  predictableActionArguments: true,
  preserveActionOrder: true,
  tsTypes: {} as import('./toggleMachine.fetched.typegen').Typegen0,
});
