import { createMachine } from 'xstate';

// This file was generated by the XState CLI, please do not edit it manually.
export const fetchedMachine = createMachine({
  id: 'Toggle Machine',
  initial: 'Off',
  states: {
    Off: {
      on: {
        toggle: {
          target: 'On',
        },
      },
    },
    On: {
      on: {
        toggle: {
          target: 'Off',
        },
      },
    },
  },
  schema: { events: {} as { type: 'toggle' } },
  predictableActionArguments: true,
  preserveActionOrder: true,
  tsTypes: {} as import('./toggleMachine.fetched.typegen').Typegen0,
});
