import { existsSync } from 'fs';
import * as fs from 'fs/promises';
import * as path from 'path';
import * as prettier from 'prettier';

const getFetchedFilePath = (filePath: string) =>
  filePath.slice(0, -path.extname(filePath).length) + '.fetched.ts';

export const doesFetchedMachineFileExist = (filePath: string) => {
  const pathToSave = getFetchedFilePath(filePath);
  return existsSync(pathToSave);
};

export const writeToFetchedMachineFile = async (opts: {
  filePath: string;
  prettyConfigString: string;
  createTypeGenFile: (
    uriArray: string[],
    { cwd }: { cwd: string },
  ) => Promise<void>;
}) => {
  const prettierConfig = await prettier.resolveConfig(opts.filePath);
  const pathToSave = getFetchedFilePath(opts.filePath);

  const machineFile = `
  import { createMachine } from 'xstate';
  
  // This file was generated by the XState CLI, please do not edit it manually.
  export const fetchedMachine = ${opts.prettyConfigString};
  `;

  await fs.writeFile(
    pathToSave,
    prettier.format(machineFile, {
      ...prettierConfig,
      parser: 'typescript',
    }),
  );

  await opts.createTypeGenFile([pathToSave], { cwd: __dirname });
};
